In [1]:
import numpy as np
import pandas as pd
import os

import datetime
from datetime import datetime

# 1 Data Gathering - SolarView

https://github.com/social-energy-atlas/solarview-data

## 1.1 Installations

In [2]:
installs = pd.read_csv('data/sea-solar-installations.csv', encoding='utf-8')
installs.head(5)

,sea-install-id,oiriginal-db,zip,fips,town,state,system-type,sector,install-date,utility,federal-cong-dist,state-senate-dist,state-house-dist,lat,long
0,southface_S53,Southface,31408.0,13051,Garden City,Georgia,Solar Hot Water,Residential,01/01/2008,Georgia Power Company,1.0,2.0,162.0,32.119290,-81.151748
1,southface_S55,Southface,30601.0,13059,Athens,Georgia,Solar Hot Water,Residential,01/01/2008,Georgia Power Company,10.0,46.0,118.0,33.976445,-83.368683
2,southface_S59,Southface,30030.0,13089,Decatur,Georgia,Solar Hot Water,Residential,01/01/2008,Georgia Power Company,5.0,42.0,83.0,33.767515,-84.308954
3,southface_S52,Southface,30005.0,13121,Alpharetta,Georgia,Solar Hot Water,Residential,01/01/2008,Sawnee EMC,6.0,48.0,25.0,34.070288,-84.202196
4,southface_S49,Southface,30281.0,13151,Stockbridge,Georgia,Solar Hot Water,Residential,01/01/2008,Georgia Power Company,13.0,10.0,111.0,33.501071,-84.257491

In [3]:
installs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2139 entries, 0 to 2138
Data columns (total 15 columns):
sea-install-id       2139 non-null object
oiriginal-db         2139 non-null object
zip                  2138 non-null float64
fips                 2139 non-null int64
town                 2099 non-null object
state                2139 non-null object
system-type          2139 non-null object
sector               2139 non-null object
install-date         2139 non-null object
utility              601 non-null object
federal-cong-dist    765 non-null float64
state-senate-dist    765 non-null float64
state-house-dist     765 non-null float64
lat                  2117 non-null float64
long                 2117 non-null float64
dtypes: float64(6), int64(1), object(8)
memory usage: 250.8+ KB

# 2 Data Assessment
## 2.1 Installations

In [4]:
installs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2139 entries, 0 to 2138
Data columns (total 15 columns):
sea-install-id       2139 non-null object
oiriginal-db         2139 non-null object
zip                  2138 non-null float64
fips                 2139 non-null int64
town                 2099 non-null object
state                2139 non-null object
system-type          2139 non-null object
sector               2139 non-null object
install-date         2139 non-null object
utility              601 non-null object
federal-cong-dist    765 non-null float64
state-senate-dist    765 non-null float64
state-house-dist     765 non-null float64
lat                  2117 non-null float64
long                 2117 non-null float64
dtypes: float64(6), int64(1), object(8)
memory usage: 250.8+ KB

- install-date is not in datetime format
- fips is not a string
- error in spelling of original database column

In [5]:
installs.sample(5)

,sea-install-id,oiriginal-db,zip,fips,town,state,system-type,sector,install-date,utility,federal-cong-dist,state-senate-dist,state-house-dist,lat,long
1925,southface_IS34,Southface,30286.0,13293,Thomaston,Georgia,Solar Electric,Utility,09/15/2016,NaN,NaN,NaN,NaN,32.915239,-84.298125
5,southface_S54,Southface,30549.0,13157,Jefferson,Georgia,Solar Hot Water,Residential,01/01/2008,Jackson EMC,9.0,47.0,31.0,34.072211,-83.638933
596,southface_SF6,Southface,30268.0,13121,Chattahoochee Hills,Georgia,Solar Electric,Residential,08/21/2010,NaN,NaN,NaN,NaN,33.523837,-84.738806
171,southface_S138,Southface,31406.0,13051,Savannah,Georgia,Solar Electric,Residential,03/15/2009,NaN,NaN,NaN,NaN,31.998868,-81.026885
562,southface_M508,Southface,31329.0,13031,Pembroke,Georgia,Solar Electric,Non-Residential,07/12/2010,NaN,NaN,NaN,NaN,32.194655,-81.633654

In [6]:
installs.shape

(2139, 15)

In [7]:
installs.isnull().sum()

sea-install-id          0
oiriginal-db            0
zip                     1
fips                    0
town                   40
state                   0
system-type             0
sector                  0
install-date            0
utility              1538
federal-cong-dist    1374
state-senate-dist    1374
state-house-dist     1374
lat                    22
long                   22
dtype: int64

In [8]:
installs.duplicated().sum()

1

- NaN present in zip, town, lat, utility, federal-cong-dist, state-senate-dist, state-house-dist, lat, and long.
- Can't check for duplicated id because of column name.
- zip is an integer and not a string

# 3 Data Cleaning

## 3.1 Copy All Dataframes

### 3.1.1 Define
Copy all dataframes for cleaning purposes.

#### 3.1.1.2 Code

In [9]:
installs_clean = installs.copy()

#### 3.1.1.3 Test

In [10]:
installs_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2139 entries, 0 to 2138
Data columns (total 15 columns):
sea-install-id       2139 non-null object
oiriginal-db         2139 non-null object
zip                  2138 non-null float64
fips                 2139 non-null int64
town                 2099 non-null object
state                2139 non-null object
system-type          2139 non-null object
sector               2139 non-null object
install-date         2139 non-null object
utility              601 non-null object
federal-cong-dist    765 non-null float64
state-senate-dist    765 non-null float64
state-house-dist     765 non-null float64
lat                  2117 non-null float64
long                 2117 non-null float64
dtypes: float64(6), int64(1), object(8)
memory usage: 250.8+ KB

## 3.2 Installations

Installations

- install-date is not in datetime format - DONE
- fips is not a string
- zip is an integer and not a string
- Drop congressional districts, as not useful.
- NaN present in zip, town, lat, utility, federal-cong-dist, state-senate-dist, state-house-dist, lat, and long.
- Can't check for duplicated id because of column name.


### 3.2.1 Rename Columns
#### 3.2.1.1 Define

## 3.2 Column Naming
### 3.2.1 Installations
#### 3.2.1.1 Define
Rename all columns so that hyphens are replaced with underscores so that future codes can be run successfully, as well as correcting any spelling errors.

#### 3.2.1.2 Code

In [11]:
installs_clean = installs_clean.rename(columns={"sea-install-id": "sea_install_id", 
                                                "oiriginal-db": "original_db", 
                                                "system-type": "system_type", 
                                                "install-date": "install_date", 
                                                "federal-cong-dist": "fed_congressional_district", 
                                                "state-senate-dist": "state_senate_district", 
                                                "state-house-dist": "state_house_district"})

#### 3.2.1.3 Test

In [12]:
installs_clean.head()

,sea_install_id,original_db,zip,fips,town,state,system_type,sector,install_date,utility,fed_congressional_district,state_senate_district,state_house_district,lat,long
0,southface_S53,Southface,31408.0,13051,Garden City,Georgia,Solar Hot Water,Residential,01/01/2008,Georgia Power Company,1.0,2.0,162.0,32.119290,-81.151748
1,southface_S55,Southface,30601.0,13059,Athens,Georgia,Solar Hot Water,Residential,01/01/2008,Georgia Power Company,10.0,46.0,118.0,33.976445,-83.368683
2,southface_S59,Southface,30030.0,13089,Decatur,Georgia,Solar Hot Water,Residential,01/01/2008,Georgia Power Company,5.0,42.0,83.0,33.767515,-84.308954
3,southface_S52,Southface,30005.0,13121,Alpharetta,Georgia,Solar Hot Water,Residential,01/01/2008,Sawnee EMC,6.0,48.0,25.0,34.070288,-84.202196
4,southface_S49,Southface,30281.0,13151,Stockbridge,Georgia,Solar Hot Water,Residential,01/01/2008,Georgia Power Company,13.0,10.0,111.0,33.501071,-84.257491

### 3.2.2 Convert install_date to datetime format
#### 3.2.2.1 Define
The install_date column should be in datetime format. Drop any unknown dates and convert those values to datetime.

#### 3.2.2.2 Code

In [13]:
installs_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2139 entries, 0 to 2138
Data columns (total 15 columns):
sea_install_id                2139 non-null object
original_db                   2139 non-null object
zip                           2138 non-null float64
fips                          2139 non-null int64
town                          2099 non-null object
state                         2139 non-null object
system_type                   2139 non-null object
sector                        2139 non-null object
install_date                  2139 non-null object
utility                       601 non-null object
fed_congressional_district    765 non-null float64
state_senate_district         765 non-null float64
state_house_district          765 non-null float64
lat                           2117 non-null float64
long                          2117 non-null float64
dtypes: float64(6), int64(1), object(8)
memory usage: 250.8+ KB

In [14]:
installs_clean['install_date'] = pd.to_datetime(installs_clean['install_date'])

#### 3.2.2.3 Test

In [15]:
installs_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2139 entries, 0 to 2138
Data columns (total 15 columns):
sea_install_id                2139 non-null object
original_db                   2139 non-null object
zip                           2138 non-null float64
fips                          2139 non-null int64
town                          2099 non-null object
state                         2139 non-null object
system_type                   2139 non-null object
sector                        2139 non-null object
install_date                  2139 non-null datetime64[ns]
utility                       601 non-null object
fed_congressional_district    765 non-null float64
state_senate_district         765 non-null float64
state_house_district          765 non-null float64
lat                           2117 non-null float64
long                          2117 non-null float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(7)
memory usage: 250.8+ KB

### 3.2.3 Convert fips, zip, and congressional district columns to strings
#### 3.2.3.1 Define
Convert the fips, zip, fed_congressional_district, state_senate_district, and state_house_district columns to string format all columns.

#### 3.2.3.2 Code

In [16]:
print(installs_clean[installs_clean['zip'].isnull()])

       sea_install_id original_db  zip   fips town    state     system_type  \
1833  southface_SF137   Southface  NaN  13053  NaN  Georgia  Solar Electric

       sector install_date utility  fed_congressional_district  \
1833  Utility   2016-06-01     NaN                         NaN

      state_senate_district  state_house_district        lat       long
1833                    NaN                   NaN  32.318057 -84.972077

In [17]:
installs_clean.drop([1833], inplace=True)
installs_clean['zip'] = installs_clean['zip'].round(0).astype(int)
installs_clean['zip'] = installs_clean['zip'].astype(str)
installs_clean['fips'] = installs_clean['fips'].astype(str)

#### 3.2.3.3 Test

In [18]:
installs_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2138 entries, 0 to 2138
Data columns (total 15 columns):
sea_install_id                2138 non-null object
original_db                   2138 non-null object
zip                           2138 non-null object
fips                          2138 non-null object
town                          2099 non-null object
state                         2138 non-null object
system_type                   2138 non-null object
sector                        2138 non-null object
install_date                  2138 non-null datetime64[ns]
utility                       601 non-null object
fed_congressional_district    765 non-null float64
state_senate_district         765 non-null float64
state_house_district          765 non-null float64
lat                           2116 non-null float64
long                          2116 non-null float64
dtypes: datetime64[ns](1), float64(5), object(9)
memory usage: 267.2+ KB

In [19]:
installs_clean.head(5)

,sea_install_id,original_db,zip,fips,town,state,system_type,sector,install_date,utility,fed_congressional_district,state_senate_district,state_house_district,lat,long
0,southface_S53,Southface,31408,13051,Garden City,Georgia,Solar Hot Water,Residential,2008-01-01,Georgia Power Company,1.0,2.0,162.0,32.119290,-81.151748
1,southface_S55,Southface,30601,13059,Athens,Georgia,Solar Hot Water,Residential,2008-01-01,Georgia Power Company,10.0,46.0,118.0,33.976445,-83.368683
2,southface_S59,Southface,30030,13089,Decatur,Georgia,Solar Hot Water,Residential,2008-01-01,Georgia Power Company,5.0,42.0,83.0,33.767515,-84.308954
3,southface_S52,Southface,30005,13121,Alpharetta,Georgia,Solar Hot Water,Residential,2008-01-01,Sawnee EMC,6.0,48.0,25.0,34.070288,-84.202196
4,southface_S49,Southface,30281,13151,Stockbridge,Georgia,Solar Hot Water,Residential,2008-01-01,Georgia Power Company,13.0,10.0,111.0,33.501071,-84.257491

### 3.2.4 Investigate town NaN values
#### 3.2.4.1 Define
Query the dataset and investigate NaN values for the town column to see if data can be retrieved to complete. Otherwise, remove observations from the dataset.

#### 3.2.4.2 Code

In [20]:
installs_clean[installs_clean['town'].isnull()]

,sea_install_id,original_db,zip,fips,town,state,system_type,sector,install_date,utility,fed_congressional_district,state_senate_district,state_house_district,lat,long
36,southface_SF131a,Southface,30305,13121,NaN,Georgia,Solar Electric,Residential,2005-12-31,NaN,NaN,NaN,NaN,33.823333,-84.399232
43,southface_SF131b,Southface,30305,13121,NaN,Georgia,Solar Electric,Residential,2006-12-31,NaN,NaN,NaN,NaN,33.823333,-84.399232
684,southface_SF126,Southface,30188,13067,NaN,Georgia,Solar Electric,Non-Residential,2010-12-14,NaN,11.0,37.0,34.0,33.983053,-84.577952
885,southface_UR01,Southface,31906,40101,NaN,Georgia,Solar Electric,Non-Residential,2011-08-01,NaN,NaN,NaN,NaN,32.475310,-84.944636
1349,southface_M1053,Southface,30054,13297,NaN,Georgia,Solar Electric,Residential,2013-02-25,NaN,NaN,NaN,NaN,33.689491,-83.819327
1353,southface_M1055,Southface,30040,13117,NaN,Georgia,Solar Electric,Residential,2013-02-28,NaN,NaN,NaN,NaN,34.265310,-84.094711
1370,southface_M1051,Southface,30143,13227,NaN,Georgia,Solar Electric,Residential,2013-05-04,NaN,NaN,NaN,NaN,34.469552,-84.428989
1382,southface_M1056,Southface,31406,13051,NaN,Georgia,Solar Electric,Residential,2013-07-12,NaN,NaN,NaN,NaN,31.975155,-81.057734
1415,southface_SF125,Southface,31018,13303,NaN,Georgia,Solar Electric,Utility,2013-12-01,Cobb EMC,10.0,26.0,128.0,33.006887,-82.558476
1451,southface_M1054,Southface,30269,13113,NaN,Georgia,Solar Electric,Non-Residential,2013-12-16,NaN,3.0,16.0,72.0,33.363500,-84.567805
1472,southface_GPC-10472,Southface,30439,13043,NaN,Georgia,Solar Electric,Utility,2014-01-29,Georgia Power Company,12.0,4.0,158.0,32.477344,-82.176718
1473,southface_GPC-10265,Southface,31006,13269,NaN,Georgia,Solar Electric,Utility,2014-01-29,Georgia Power Company,2.0,15.0,139.0,32.635875,-84.252549
1483,southface_SF124,Southface,31409,13051,NaN,Georgia,Solar Electric,Non-Residential,2014-03-25,NaN,NaN,NaN,NaN,32.028773,-81.126069
1490,southface_SF127,Southface,30230,13199,NaN,Georgia,Solar Electric,Residential,2014-05-09,NaN,NaN,NaN,NaN,33.070294,-84.782262
1493,southface_SSW19,Southface,30650,13211,NaN,Georgia,Solar Electric,Residential,2014-06-20,NaN,NaN,NaN,NaN,33.576857,-83.373777
1497,southface_SSW20,Southface,30044,13135,NaN,Georgia,Solar Electric,Residential,2014-07-30,NaN,NaN,NaN,NaN,33.890809,-84.093166
1506,southface_SSW22,Southface,30056,13211,NaN,Georgia,Solar Electric,Residential,2014-09-19,NaN,NaN,NaN,NaN,33.526066,-83.680398
1507,southface_GPC-10133,Southface,30120,13015,NaN,Georgia,Solar Electric,Residential,2014-09-23,NaN,NaN,NaN,NaN,34.137969,-84.803703
1508,southface_HS56,Southface,30222,13199,NaN,Georgia,Solar Electric,Utility,2014-09-23,Georgia Power Company,3.0,29.0,137.0,33.044905,-84.714463
1509,southface_SSW23,Southface,30533,13187,NaN,Georgia,Solar Electric,Non-Residential,2014-09-28,NaN,NaN,NaN,NaN,34.556237,-83.974142
1517,southface_GPC-10190,Southface,30805,13033,NaN,Georgia,Solar Electric,Non-Residential,2014-10-09,NaN,NaN,NaN,NaN,33.274090,-82.233076
1518,southface_GPC-10140,Southface,30553,13119,NaN,Georgia,Solar Electric,Non-Residential,2014-10-13,NaN,NaN,NaN,NaN,34.442221,-83.120987
1529,southface_SSW24,Southface,30625,13211,NaN,Georgia,Solar Electric,Residential,2014-11-08,NaN,NaN,NaN,NaN,33.584430,-83.336506
1551,southface_GPC-10549,Southface,30030,13089,NaN,Georgia,Solar Electric,Non-Residential,2014-12-11,NaN,NaN,NaN,NaN,33.765550,-84.293923
1552,southface_GPC-10418,Southface,30417,13109,NaN,Georgia,Solar Electric,Utility,2014-12-11,Georgia Power Company,12.0,4.0,157.0,32.148029,-81.942174
1558,southface_GPC-10451,Southface,30030,13089,NaN,Georgia,Solar Electric,Non-Residential,2014-12-17,NaN,NaN,NaN,NaN,33.771536,-84.289808
1561,southface_GPC-10534,Southface,30030,13089,NaN,Georgia,Solar Electric,Non-Residential,2014-12-23,NaN,NaN,NaN,NaN,33.768633,-84.297126
1562,southface_GPC-10782,Southface,31525,13127,NaN,Georgia,Solar Electric,Non-Residential,2014-12-23,NaN,NaN,NaN,NaN,31.213865,-81.482539
1565,southface_SSW25,Southface,30549,13157,NaN,Georgia,Solar Electric,Non-Residential,2014-12-31,NaN,NaN,NaN,NaN,34.098618,-83.576572
1577,southface_GPC-10640,Southface,30124,13115,NaN,Georgia,Solar Electric,Utility,2015-01-08,NaN,NaN,NaN,NaN,34.106466,-85.363595
1581,southface_GPC-10779,Southface,30909,13245,NaN,Georgia,Solar Electric,Non-Residential,2015-01-12,NaN,NaN,NaN,NaN,33.468797,-82.080681
1583,southface_GPC-10538,Southface,39845,13253,NaN,Georgia,Solar Electric,Non-Residential,2015-01-16,NaN,NaN,NaN,NaN,31.061522,-84.899261
1584,southface_GPC-10389,Southface,31796,13321,NaN,Georgia,Solar Electric,Utility,2015-01-17,Georgia Power Company,8.0,13.0,152.0,31.832105,-83.950435
1585,southface_GPC-10271,Southface,31012,13091,NaN,Georgia,Solar Electric,Utility,2015-01-21,NaN,NaN,NaN,NaN,32.388299,-83.142471
1587,southface_GPC-10542,Southface,30030,13089,NaN,Georgia,Solar Electric,Non-Residential,2015-01-27,NaN,NaN,NaN,NaN,33.766010,-84.295146
1606,southface_GPC-10001,Southface,31091,13093,NaN,Georgia,Solar Electric,Utility,2015-02-17,NaN,2.0,13.0,139.0,32.256800,-83.744800
1607,southface_GPC-10650,Southface,30165,13115,NaN,Georgia,Solar Electric,Utility,2015-02-27,NaN,NaN,NaN,NaN,34.260040,-85.301251
1611,southface_GPC-10192,Southface,30328,13121,NaN,Georgia,Solar Electric,Non-Residential,2015-03-14,NaN,NaN,NaN,NaN,33.924649,-84.351386
1991,southface_SF149,Southface,31006,13269,NaN,Georgia,Solar Electric,Utility,2016-12-22,NaN,NaN,NaN,NaN,32.561115,-84.276448

In [21]:
print(installs_clean['zip'][36])
print(installs_clean['zip'][43])
print(installs_clean['zip'][684])
print(installs_clean['zip'][885])
print(installs_clean['zip'][1349])

30305
30305
30188
31906
30054

In [22]:
installs_clean.at[36, 'town'] = 'Atlanta'
installs_clean.at[43, 'town'] = 'Atlanta'
installs_clean.at[684, 'town'] = 'Woodstock'
installs_clean.at[885, 'town'] = 'Columbus'
installs_clean.at[1349, 'town'] = 'Oxford'

In [23]:
print(installs_clean['zip'][1353])
print(installs_clean['zip'][1370])
print(installs_clean['zip'][1382])
print(installs_clean['zip'][1415])
print(installs_clean['zip'][1451])

30040
30143
31406
31018
30269

In [24]:
installs_clean.at[1382, 'town'] = 'Savannah'
installs_clean.at[1451, 'town'] = 'Peachtree City'
installs_clean.at[1353, 'town'] = 'Cumming'
installs_clean.at[1370, 'town'] = 'Jasper'
installs_clean.at[1415, 'town'] = 'Davisboro'

In [25]:
print(installs_clean['zip'][1472])
print(installs_clean['zip'][1473])
print(installs_clean['zip'][1483])
print(installs_clean['zip'][1490])
print(installs_clean['zip'][1493])

30439
31006
31409
30230
30650

In [26]:
installs_clean.at[1472, 'town'] = 'Metter'
installs_clean.at[1473, 'town'] = 'Butler'
installs_clean.at[1483, 'town'] = 'Savannah'
installs_clean.at[1490, 'town'] = 'Hogansville'
installs_clean.at[1493, 'town'] = 'Madison'

In [27]:
print(installs_clean['zip'][1497])
print(installs_clean['zip'][1506])
print(installs_clean['zip'][1507])
print(installs_clean['zip'][1508])
print(installs_clean['zip'][1509])

30044
30056
30120
30222
30533

In [28]:
installs_clean.at[1497, 'town'] = 'Lawrenceville'
installs_clean.at[1506, 'town'] = 'Newborn'
installs_clean.at[1507, 'town'] = 'Cartersville'
installs_clean.at[1508, 'town'] = 'Greenville'
installs_clean.at[1509, 'town'] = 'Dahlonega'

In [29]:
print(installs_clean['zip'][1517])
print(installs_clean['zip'][1518])
print(installs_clean['zip'][1529])
print(installs_clean['zip'][1551])
print(installs_clean['zip'][1552])

30805
30553
30625
30030
30417

In [30]:
installs_clean.at[1517, 'town'] = 'Augusta'
installs_clean.at[1518, 'town'] = 'Lavonia'
installs_clean.at[1529, 'town'] = 'Buckhead'
installs_clean.at[1551, 'town'] = 'Decatur'
installs_clean.at[1552, 'town'] = 'Claxton'

In [31]:
print(installs_clean['zip'][1558])
print(installs_clean['zip'][1561])
print(installs_clean['zip'][1562])
print(installs_clean['zip'][1565])
print(installs_clean['zip'][1577])

30030
30030
31525
30549
30124

In [32]:
installs_clean.at[1558, 'town'] = 'Decatur'
installs_clean.at[1561, 'town'] = 'Decatur'
installs_clean.at[1562, 'town'] = 'Brunswick'
installs_clean.at[1565, 'town'] = 'Jefferson'
installs_clean.at[1577, 'town'] = 'Cave Spring'

In [33]:
print(installs_clean['zip'][1581])
print(installs_clean['zip'][1583])
print(installs_clean['zip'][1584])
print(installs_clean['zip'][1585])
print(installs_clean['zip'][1587])

30909
39845
31796
31012
30030

In [34]:
installs_clean.at[1581, 'town'] = 'Augusta'
installs_clean.at[1583, 'town'] = 'Donalsonville'
installs_clean.at[1584, 'town'] = 'Acorn Pond'
installs_clean.at[1585, 'town'] = 'Chester'
installs_clean.at[1587, 'town'] = 'Decatur'

In [35]:
print(installs_clean['zip'][1606])
print(installs_clean['zip'][1607])
print(installs_clean['zip'][1611])
print(installs_clean['zip'][1991])

31091
30165
30328
31006

In [36]:
installs_clean.at[1606, 'town'] = 'Unadilla'
installs_clean.at[1607, 'town'] = 'Rome'
installs_clean.at[1611, 'town'] = 'Sandy Springs'
installs_clean.at[1991, 'town'] = 'Butler'

#### 3.2.4.3 Test

In [37]:
print(installs_clean[installs_clean['town'].isnull()])

Empty DataFrame
Columns: [sea_install_id, original_db, zip, fips, town, state, system_type, sector, install_date, utility, fed_congressional_district, state_senate_district, state_house_district, lat, long]
Index: []

### 3.2.5 Remove all observations with no latitude or longitude
#### 3.2.5.1 Define
Query the dataset and remove all NaN lat/long observations.

#### 3.2.5.2 Code

In [38]:
installs_clean[installs_clean['lat'].isnull()]

,sea_install_id,original_db,zip,fips,town,state,system_type,sector,install_date,utility,fed_congressional_district,state_senate_district,state_house_district,lat,long
29,nrel_NREL1,NREL,31405,13051,Savannah,Georgia,Solar Electric,Residential,1997-10-13,NaN,NaN,NaN,NaN,NaN,NaN
31,nrel_NREL2,NREL,30308,13121,Atlanta,Georgia,Solar Electric,Non-Residential,2002-01-01,NaN,NaN,NaN,NaN,NaN,NaN
90,nrel_NREL3,NREL,30022,13121,Alpharetta,Georgia,Solar Electric,Residential,2008-09-02,NaN,NaN,NaN,NaN,NaN,NaN
217,nrel_NREL4,NREL,30305,13121,Atlanta,Georgia,Solar Electric,Residential,2009-07-03,NaN,NaN,NaN,NaN,NaN,NaN
284,nrel_NREL5,NREL,31321,13029,Pembroke,Georgia,Solar Electric,Non-Residential,2009-09-25,NaN,NaN,NaN,NaN,NaN,NaN
290,nrel_NREL6,NREL,30541,13111,Epworth,Georgia,Solar Electric,Unknown,2009-09-30,NaN,NaN,NaN,NaN,NaN,NaN
339,nrel_NREL7,NREL,30513,13111,Blue Ridge,Georgia,Solar Electric,Unknown,2009-12-08,NaN,NaN,NaN,NaN,NaN,NaN
341,nrel_NREL8,NREL,30269,13113,Peachtree City,Georgia,Solar Electric,Non-Residential,2009-12-15,NaN,NaN,NaN,NaN,NaN,NaN
358,nrel_NREL9,NREL,30055,13159,Mansfield,Georgia,Solar Electric,Residential,2010-01-03,NaN,NaN,NaN,NaN,NaN,NaN
388,nrel_NREL10,NREL,30721,13313,Dalton,Georgia,Solar Electric,Unknown,2010-01-08,NaN,NaN,NaN,NaN,NaN,NaN
409,nrel_NREL11,NREL,30004,13117,Alpharetta,Georgia,Solar Electric,Non-Residential,2010-01-25,NaN,NaN,NaN,NaN,NaN,NaN
455,nrel_NREL12,NREL,30522,13123,Cherry Log,Georgia,Solar Electric,Unknown,2010-03-05,NaN,NaN,NaN,NaN,NaN,NaN
549,nrel_NREL13,NREL,30725,13295,Flintstone,Georgia,Solar Electric,Unknown,2010-06-28,NaN,NaN,NaN,NaN,NaN,NaN
577,nrel_NREL14,NREL,30172,13115,Shannon,Georgia,Solar Electric,Unknown,2010-07-28,NaN,NaN,NaN,NaN,NaN,NaN
583,nrel_NREL15,NREL,30004,13117,Alpharetta,Georgia,Solar Electric,Residential,2010-08-06,NaN,NaN,NaN,NaN,NaN,NaN
762,nrel_NREL16,NREL,30004,13117,Alpharetta,Georgia,Solar Electric,Non-Residential,2011-03-01,NaN,NaN,NaN,NaN,NaN,NaN
763,nrel_NREL17,NREL,31021,13175,Dublin,Georgia,Solar Electric,Non-Residential,2011-03-01,NaN,NaN,NaN,NaN,NaN,NaN
1001,nrel_NREL18,NREL,31206,13021,Macon,Georgia,Solar Electric,Non-Residential,2011-12-14,NaN,NaN,NaN,NaN,NaN,NaN
1007,nrel_NREL19,NREL,30906,13245,Augusta,Georgia,Solar Electric,Non-Residential,2011-12-15,NaN,NaN,NaN,NaN,NaN,NaN
1260,nrel_NREL20,NREL,30093,13135,Norcross,Georgia,Solar Electric,Non-Residential,2012-09-05,NaN,NaN,NaN,NaN,NaN,NaN
1337,nrel_NREL21,NREL,30622,13059,Bogart,Georgia,Solar Electric,Non-Residential,2013-01-14,NaN,NaN,NaN,NaN,NaN,NaN
1644,nrel_NREL22,NREL,30458,13031,Statesboro,Georgia,Solar Electric,Residential,2015-05-02,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
installs_clean[installs_clean['lat'].isnull()].shape

(22, 15)

In [40]:
installs_clean.drop([29,31,90,217,284,290,339,341,358,388,409,455,549,577,583,762,763,1001,1007,1260,1337,1644], inplace=True)

#### 3.2.5.2 Test

In [41]:
installs_clean[installs_clean['lat'].isnull()]

Empty DataFrame
Columns: [sea_install_id, original_db, zip, fips, town, state, system_type, sector, install_date, utility, fed_congressional_district, state_senate_district, state_house_district, lat, long]
Index: []

In [42]:
installs_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2116 entries, 0 to 2138
Data columns (total 15 columns):
sea_install_id                2116 non-null object
original_db                   2116 non-null object
zip                           2116 non-null object
fips                          2116 non-null object
town                          2116 non-null object
state                         2116 non-null object
system_type                   2116 non-null object
sector                        2116 non-null object
install_date                  2116 non-null datetime64[ns]
utility                       601 non-null object
fed_congressional_district    765 non-null float64
state_senate_district         765 non-null float64
state_house_district          765 non-null float64
lat                           2116 non-null float64
long                          2116 non-null float64
dtypes: datetime64[ns](1), float64(5), object(9)
memory usage: 264.5+ KB

In [43]:
installs_clean.drop(["fed_congressional_district", "state_senate_district", "state_house_district"], axis = 1, inplace = True)

In [44]:
installs_clean[installs_clean['utility'].isnull()]

,sea_install_id,original_db,zip,fips,town,state,system_type,sector,install_date,utility,lat,long
27,southface_SF24,Southface,30318,13121,Atlanta,Georgia,Solar Electric,Non-Residential,1996-01-01,NaN,33.775772,-84.402532
28,southface_SF25,Southface,30318,13121,Atlanta,Georgia,Solar Hot Water,Non-Residential,1996-01-01,NaN,33.775772,-84.402532
30,southface_SF33,Southface,30240,13285,LaGrange,Georgia,Solar Electric,Non-Residential,1999-02-01,NaN,33.000525,-85.056206
32,southface_SF20,Southface,30064,13067,Marietta,Georgia,Solar Electric,Residential,2003-01-01,NaN,33.934810,-84.640828
33,southface_SF96,Southface,31774,13155,Ocilla,Georgia,Solar Electric,Non-Residential,2005-08-18,NaN,31.581931,-83.240312
...,...,...,...,...,...,...,...,...,...,...,...,...
2134,southface_RS17-1-0003,Southface,30339,13067,Atlanta,Georgia,Solar Electric,Non-Residential,2017-08-30,NaN,33.880656,-84.470292
2135,southface_CS113,Southface,30306,13121,Atlanta,Georgia,Solar Electric,Residential,2017-08-30,NaN,33.778986,-84.354015
2136,southface_AS10,Southface,30268,13077,Palmetto,Georgia,Solar Electric,Residential,2017-09-01,NaN,33.498070,-84.718732
2137,southface_SF161,Southface,30810,13125,Gibson,Georgia,Solar Electric,Utility,2017-09-13,NaN,33.210600,-82.602739
2138,southface_AES118,Southface,30017,13135,Grayson,Georgia,Solar Electric,Residential,2017-02-28,NaN,33.891688,-83.964515

In [45]:
utilities_needed = installs_clean.copy()

In [46]:
utilities_needed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2116 entries, 0 to 2138
Data columns (total 12 columns):
sea_install_id    2116 non-null object
original_db       2116 non-null object
zip               2116 non-null object
fips              2116 non-null object
town              2116 non-null object
state             2116 non-null object
system_type       2116 non-null object
sector            2116 non-null object
install_date      2116 non-null datetime64[ns]
utility           601 non-null object
lat               2116 non-null float64
long              2116 non-null float64
dtypes: datetime64[ns](1), float64(2), object(9)
memory usage: 214.9+ KB

In [47]:
utilities_needed.drop(["sea_install_id", "original_db","fips","town","state","system_type","sector","install_date","lat","long"], axis = 1, inplace = True)

In [48]:
utilities_needed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2116 entries, 0 to 2138
Data columns (total 2 columns):
zip        2116 non-null object
utility    601 non-null object
dtypes: object(2)
memory usage: 49.6+ KB

In [49]:
utilities_needed = utilities_needed[utilities_needed['utility'].isnull()]

In [50]:
utilities_needed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1515 entries, 27 to 2138
Data columns (total 2 columns):
zip        1515 non-null object
utility    0 non-null object
dtypes: object(2)
memory usage: 35.5+ KB

In [51]:
utilities_needed.to_csv('utilities_needed.csv', encoding='utf-8', index=False)

In [52]:
utils_identified = pd.read_csv('utils_identified.csv', encoding='utf-8')
utils_identified.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 2 columns):
zip        360 non-null int64
utility    360 non-null object
dtypes: int64(1), object(1)
memory usage: 5.8+ KB

In [53]:
utils_identified["zip"] = utils_identified['zip'].astype(str)
utils_identified.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 2 columns):
zip        360 non-null object
utility    360 non-null object
dtypes: object(2)
memory usage: 5.8+ KB

In [54]:
installs_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2116 entries, 0 to 2138
Data columns (total 12 columns):
sea_install_id    2116 non-null object
original_db       2116 non-null object
zip               2116 non-null object
fips              2116 non-null object
town              2116 non-null object
state             2116 non-null object
system_type       2116 non-null object
sector            2116 non-null object
install_date      2116 non-null datetime64[ns]
utility           601 non-null object
lat               2116 non-null float64
long              2116 non-null float64
dtypes: datetime64[ns](1), float64(2), object(9)
memory usage: 214.9+ KB

In [55]:
utils_identified_merge = pd.merge(installs_clean, utils_identified, on = 'zip', how = 'left')

In [56]:
utils_identified_merge.sample(5)

,sea_install_id,original_db,zip,fips,town,state,system_type,sector,install_date,utility_x,lat,long,utility_y
2039,southface_HS143,Southface,31401,13051,Savannah,Georgia,Solar Electric,Residential,2015-12-01,NaN,32.070071,-81.087706,NaN
465,southface_S349,Southface,30135,13097,Douglasville,Georgia,Solar Hot Water,Residential,2010-02-01,Unknown,33.602018,-84.826880,NaN
2017,southface_HS164,Southface,30680,13013,Winder,Georgia,Solar Electric,Residential,2015-12-01,NaN,33.975336,-83.741959,NaN
2141,southface_AES041,Southface,30607,13157,Athens,Georgia,Solar Electric,Residential,2016-06-20,NaN,33.999717,-83.501336,NaN
1300,southface_M790,Southface,30306,13121,Atlanta,Georgia,Solar Hot Water,Residential,2012-05-03,Unknown,33.784396,-84.351787,NaN

In [57]:
utils_identified_merge[utils_identified_merge['utility_x'].isnull()]

,sea_install_id,original_db,zip,fips,town,state,system_type,sector,install_date,utility_x,lat,long,utility_y
31,southface_SF24,Southface,30318,13121,Atlanta,Georgia,Solar Electric,Non-Residential,1996-01-01,NaN,33.775772,-84.402532,NaN
32,southface_SF25,Southface,30318,13121,Atlanta,Georgia,Solar Hot Water,Non-Residential,1996-01-01,NaN,33.775772,-84.402532,NaN
33,southface_SF33,Southface,30240,13285,LaGrange,Georgia,Solar Electric,Non-Residential,1999-02-01,NaN,33.000525,-85.056206,NaN
34,southface_SF20,Southface,30064,13067,Marietta,Georgia,Solar Electric,Residential,2003-01-01,NaN,33.934810,-84.640828,NaN
35,southface_SF96,Southface,31774,13155,Ocilla,Georgia,Solar Electric,Non-Residential,2005-08-18,NaN,31.581931,-83.240312,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2470,southface_SF161,Southface,30810,13125,Gibson,Georgia,Solar Electric,Utility,2017-09-13,NaN,33.210600,-82.602739,Washington Elec Member Corp
2471,southface_AES118,Southface,30017,13135,Grayson,Georgia,Solar Electric,Residential,2017-02-28,NaN,33.891688,-83.964515,City of Lawrenceville - (GA)
2472,southface_AES118,Southface,30017,13135,Grayson,Georgia,Solar Electric,Residential,2017-02-28,NaN,33.891688,-83.964515,Georgia Power Co
2473,southface_AES118,Southface,30017,13135,Grayson,Georgia,Solar Electric,Residential,2017-02-28,NaN,33.891688,-83.964515,Jackson Electric Member Corp - (GA)
2474,southface_AES118,Southface,30017,13135,Grayson,Georgia,Solar Electric,Residential,2017-02-28,NaN,33.891688,-83.964515,Walton Electric Member Corp

In [58]:
utils_identified_merge.utility_x.fillna(utils_identified_merge.utility_y, inplace=True)
del utils_identified_merge['utility_y']
utils_identified_merge.head(4)

,sea_install_id,original_db,zip,fips,town,state,system_type,sector,install_date,utility_x,lat,long
0,southface_S53,Southface,31408,13051,Garden City,Georgia,Solar Hot Water,Residential,2008-01-01,Georgia Power Company,32.119290,-81.151748
1,southface_S55,Southface,30601,13059,Athens,Georgia,Solar Hot Water,Residential,2008-01-01,Georgia Power Company,33.976445,-83.368683
2,southface_S59,Southface,30030,13089,Decatur,Georgia,Solar Hot Water,Residential,2008-01-01,Georgia Power Company,33.767515,-84.308954
3,southface_S52,Southface,30005,13121,Alpharetta,Georgia,Solar Hot Water,Residential,2008-01-01,Sawnee EMC,34.070288,-84.202196

In [59]:
utils_identified_merge["utility_x"].fillna("Unknown", inplace = True)

In [60]:
utils_identified_merge.head(25)

,sea_install_id,original_db,zip,fips,town,state,system_type,sector,install_date,utility_x,lat,long
0,southface_S53,Southface,31408,13051,Garden City,Georgia,Solar Hot Water,Residential,2008-01-01,Georgia Power Company,32.119290,-81.151748
1,southface_S55,Southface,30601,13059,Athens,Georgia,Solar Hot Water,Residential,2008-01-01,Georgia Power Company,33.976445,-83.368683
2,southface_S59,Southface,30030,13089,Decatur,Georgia,Solar Hot Water,Residential,2008-01-01,Georgia Power Company,33.767515,-84.308954
3,southface_S52,Southface,30005,13121,Alpharetta,Georgia,Solar Hot Water,Residential,2008-01-01,Sawnee EMC,34.070288,-84.202196
4,southface_S49,Southface,30281,13151,Stockbridge,Georgia,Solar Hot Water,Residential,2008-01-01,Georgia Power Company,33.501071,-84.257491
5,southface_S54,Southface,30549,13157,Jefferson,Georgia,Solar Hot Water,Residential,2008-01-01,Jackson EMC,34.072211,-83.638933
6,southface_S54,Southface,30549,13157,Jefferson,Georgia,Solar Hot Water,Residential,2008-01-01,Jackson EMC,34.072211,-83.638933
7,southface_S64,Southface,30549,13157,Jefferson,Georgia,Solar Hot Water,Residential,2008-01-01,Jackson EMC,34.084172,-83.657030
8,southface_S64,Southface,30549,13157,Jefferson,Georgia,Solar Hot Water,Residential,2008-01-01,Jackson EMC,34.084172,-83.657030
9,southface_S58,Southface,30650,13211,Madison,Georgia,Solar Hot Water,Residential,2008-01-01,Georgia Power Company,33.595032,-83.460743
10,southface_S65,Southface,30650,13211,Madison,Georgia,Solar Hot Water,Residential,2008-01-01,Georgia Power Company,33.595171,-83.454767
11,southface_S50,Southface,30677,13219,Watkinsville,Georgia,Solar Hot Water,Residential,2008-01-01,Georgia Power Company,33.867751,-83.380991
12,southface_S51,Southface,30621,13219,Bishop,Georgia,Solar Hot Water,Residential,2008-01-01,Walton EMC,33.860071,-83.528172
13,southface_S57,Southface,30546,13281,Hiawassee,Georgia,Solar Hot Water,Residential,2008-01-01,Blue Ridge Mountain EMC,34.928972,-83.732366
14,southface_S231,Southface,30530,13011,Commerce,Georgia,Solar Hot Water,Residential,2009-01-01,Jackson EMC,34.236969,-83.394848
15,southface_S231,Southface,30530,13011,Commerce,Georgia,Solar Hot Water,Residential,2009-01-01,Jackson EMC,34.236969,-83.394848
16,southface_S231,Southface,30530,13011,Commerce,Georgia,Solar Hot Water,Residential,2009-01-01,Jackson EMC,34.236969,-83.394848
17,southface_S215,Southface,31419,13051,Savannah,Georgia,Solar Hot Water,Residential,2009-01-01,Georgia Power Company,32.010782,-81.261475
18,southface_S165,Southface,30066,13067,Marietta,Georgia,Solar Hot Water,Residential,2009-01-01,Cobb EMC,34.011397,-84.537877
19,southface_S206,Southface,30152,13067,Kennesaw,Georgia,Solar Hot Water,Residential,2009-01-01,Cobb EMC,34.017425,-84.650024
20,southface_S171,Southface,30345,13089,Atlanta,Georgia,Solar Hot Water,Residential,2009-01-01,Georgia Power Company,33.857668,-84.286903
21,southface_S214,Southface,30340,13089,Atlanta,Georgia,Solar Hot Water,Non-Residential,2009-01-01,Unknown,33.897592,-84.269243
22,southface_S166,Southface,30559,13111,Mineral Bluff,Georgia,Solar Hot Water,Residential,2009-01-01,Blue Ridge Mountain EMC,34.946957,-84.281265
23,southface_S210,Southface,30513,13111,Blue Ridge,Georgia,Solar Hot Water,Residential,2009-01-01,Blue Ridge Mountain EMC,34.866290,-84.323649
24,southface_S230,Southface,30513,13111,Blue Ridge,Georgia,Solar Hot Water,Residential,2009-01-01,Blue Ridge Mountain EMC,34.863008,-84.335677

In [61]:
utils_identified_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2475 entries, 0 to 2474
Data columns (total 12 columns):
sea_install_id    2475 non-null object
original_db       2475 non-null object
zip               2475 non-null object
fips              2475 non-null object
town              2475 non-null object
state             2475 non-null object
system_type       2475 non-null object
sector            2475 non-null object
install_date      2475 non-null datetime64[ns]
utility_x         2475 non-null object
lat               2475 non-null float64
long              2475 non-null float64
dtypes: datetime64[ns](1), float64(2), object(9)
memory usage: 251.4+ KB

In [62]:
utils_identified_merge['sea_install_id'].duplicated().sum()

365

In [63]:
utils_identified_merge['sea_install_id'].drop_duplicates(keep=False,inplace=True)

In [64]:
utils_identified_merge['sea_install_id'].duplicated().sum()

0

In [65]:
utils_identified_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2475 entries, 0 to 2474
Data columns (total 12 columns):
sea_install_id    2475 non-null object
original_db       2475 non-null object
zip               2475 non-null object
fips              2475 non-null object
town              2475 non-null object
state             2475 non-null object
system_type       2475 non-null object
sector            2475 non-null object
install_date      2475 non-null datetime64[ns]
utility_x         2475 non-null object
lat               2475 non-null float64
long              2475 non-null float64
dtypes: datetime64[ns](1), float64(2), object(9)
memory usage: 246.9+ KB

In [66]:
utils_identified_merge.sample(45)

,sea_install_id,original_db,zip,fips,town,state,system_type,sector,install_date,utility_x,lat,long
561,southface_M14,Southface,30461,13031,Statesboro,Georgia,Solar Hot Water,Residential,2010-04-29,Georgia Power Company,32.416106,-81.748711
702,southface_M217,Southface,30457,13283,Soperton,Georgia,Solar Electric,Residential,2010-09-21,Georgia Power Co,32.389326,-82.572723
847,southface_M273,Southface,30110,13045,Bremen,Georgia,Solar Electric,Non-Residential,2011-01-26,Unknown,33.678335,-85.086107
356,southface_S121,Southface,30064,13067,Marietta,Georgia,Solar Electric,Residential,2009-10-19,Unknown,33.944774,-84.595855
254,southface_S176,Southface,30813,13073,Grovetown,Georgia,Solar Hot Water,Residential,2009-07-14,Georgia Power Company,33.459535,-82.220175
1401,southface_SF34,Southface,30602,13059,Athens,Georgia,Solar Electric,Non-Residential,2012-08-01,Georgia Power Co,33.955251,-83.373211
1859,southface_SSM21,Southface,31308,13029,Black Creek,Georgia,Solar Electric,Residential,2015-02-05,Georgia Power Company,32.167309,-81.503133
315,southface_S198,Southface,30349,13121,Atlanta,Georgia,Solar Hot Water,Residential,2009-09-12,Unknown,33.629506,-84.522003
2369,southface_CS38,Southface,30030,13089,Decatur,Georgia,Solar Electric,Residential,2017-03-24,Unknown,33.787200,-84.281700
862,southface_SF76,Southface,30545,13311,Helen,Georgia,Solar Electric,Non-Residential,2011-02-05,Habersham Electric Membership Corp,34.699801,-83.723791
2419,southface_SA20,Southface,30417,13109,Claxton,Georgia,Solar Electric,Utility,2017-06-30,Canoochee Electric Member Corp,32.140714,-81.956551
463,southface_S247,Southface,30102,13057,Acworth,Georgia,Solar Electric,Residential,2010-02-01,Unknown,34.098082,-84.650282
601,southface_M26,Southface,31324,13029,Richmond Hill,Georgia,Solar Hot Water,Residential,2010-06-15,Coastal Electric Cooperative,31.845012,-81.334347
1692,southface_RS18,Southface,31021,13175,Dublin,Georgia,Solar Electric,Utility,2014-01-07,Unknown,32.520350,-82.943616
2272,southface_AES103,Southface,30683,13059,Winterville,Georgia,Solar Electric,Residential,2016-11-11,Unknown,33.959804,-83.272036
1655,southface_HS52,Southface,39819,13087,Bainbridge,Georgia,Solar Electric,Utility,2013-12-14,Georgia Power Co,30.996961,-84.518647
1447,southface_M913,Southface,31534,13069,Douglas,Georgia,Solar Electric,Non-Residential,2012-09-18,City of Douglas,31.514780,-82.894104
204,southface_S137,Southface,31405,13051,Savannah,Georgia,Solar Electric,Residential,2009-04-05,Georgia Power Company,32.009997,-81.229822
398,southface_S342,Southface,30291,13121,Union City,Georgia,Solar Hot Water,Residential,2010-01-02,Unknown,33.549288,-84.529131
1925,southface_GPC-10956,Southface,31057,13193,Marshallville,Georgia,Solar Electric,Utility,2015-05-28,Flint Electric Membership Corp,32.395943,-83.988751
183,southface_SF47,Southface,30327,13121,Sandy Springs,Georgia,Solar Electric,Non-Residential,2009-01-30,Unknown,33.902135,-84.420658
399,southface_S342,Southface,30291,13121,Union City,Georgia,Solar Hot Water,Residential,2010-01-02,Unknown,33.549288,-84.529131
792,southface_S397,Southface,30016,13217,Covington,Georgia,Solar Hot Water,Residential,2010-12-16,Unknown,33.444228,-83.860061
2338,southface_CS69,Southface,30701,13129,Calhoun,Georgia,Solar Electric,Non-Residential,2017-02-14,Unknown,34.507434,-84.957069
1118,southface_M396,Southface,30513,13111,Blue Ridge,Georgia,Solar Electric,Residential,2011-12-01,Unknown,34.849898,-84.348499
1529,southface_RW05,Southface,30701,13129,Calhoun,Georgia,Solar Electric,Non-Residential,2013-02-01,Unknown,34.507893,-84.987296
287,southface_S298,Southface,30906,13245,Augusta,Georgia,Solar Hot Water,Residential,2009-08-19,Jefferson Energy Cooperative,33.329475,-82.006827
2101,southface_AES020,Southface,30019,13135,Dacula,Georgia,Solar Electric,Residential,2016-05-09,Jackson Electric Member Corp - (GA),34.058846,-83.899623
2378,southface_CS81,Southface,30030,13089,Decatur,Georgia,Solar Electric,Residential,2017-04-10,Unknown,33.766469,-84.309090
97,southface_S83,Southface,30458,13031,Statesboro,Georgia,Solar Hot Water,Residential,2008-08-30,Excelsior EMC,32.398212,-81.867398
374,southface_S224,Southface,31326,13103,Rincon,Georgia,Solar Hot Water,Residential,2009-11-20,Georgia Power Company,32.299646,-81.245486
701,southface_M217,Southface,30457,13283,Soperton,Georgia,Solar Electric,Residential,2010-09-21,Altamaha Electric Member Corp,32.389326,-82.572723
290,southface_S126,Southface,30224,13255,Griffin,Georgia,Solar Electric,Residential,2009-08-21,City of Griffin - (GA),33.239291,-84.264056
1938,southface_HS99,Southface,30080,13067,Smyrna,Georgia,Solar Electric,Non-Residential,2015-06-01,City of Marietta - (GA),33.893860,-84.498348
2032,southface_HS133,Southface,31406,13051,Savannah,Georgia,Solar Electric,Residential,2015-12-01,Unknown,31.939257,-81.123567
1801,southface_HS77,Southface,31006,13269,Butler,Georgia,Solar Electric,Non-Residential,2014-12-01,Unknown,32.557328,-84.237685
2466,southface_CS113,Southface,30306,13121,Atlanta,Georgia,Solar Electric,Residential,2017-08-30,Unknown,33.778986,-84.354015
2348,southface_HS201,Southface,31513,13001,Baxley,Georgia,Solar Electric,Utility,2017-03-01,Unknown,31.737400,-82.361877
2309,southface_SF153,Southface,30439,13043,Metter,Georgia,Solar Electric,Utility,2016-12-21,Canoochee Electric Member Corp,32.428831,-82.103538
567,southface_S392,Southface,30076,13135,Norcross,Georgia,Solar Hot Water,Non-Residential,2010-05-06,Unknown,33.920981,-84.211139
2409,southface_RS17-1-0001,Southface,30534,13085,Dawnsonville,Georgia,Solar Electric,Non-Residential,2017-06-15,Unknown,34.592157,-84.208334
1524,southface_SF52,Southface,30655,13297,Monroe,Georgia,Solar Electric,Non-Residential,2013-01-20,Unknown,33.753960,-83.723652
1876,southface_AES013,Southface,30518,13135,Sugar Hill,Georgia,Solar Electric,Residential,2015-03-01,Unknown,34.126362,-84.057348
1817,southface_UR11,Southface,30820,13125,Mitchell,Georgia,Solar Electric,Utility,2014-12-17,Unknown,33.252356,-82.656825
2445,southface_CS109,Southface,30030,13089,Decatur,Georgia,Solar Electric,Residential,2017-07-17,Unknown,33.759720,-84.287414

In [67]:
utils_identified_merge['utility'] = utils_identified_merge['utility_x']

In [68]:
utils_identified_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2475 entries, 0 to 2474
Data columns (total 13 columns):
sea_install_id    2475 non-null object
original_db       2475 non-null object
zip               2475 non-null object
fips              2475 non-null object
town              2475 non-null object
state             2475 non-null object
system_type       2475 non-null object
sector            2475 non-null object
install_date      2475 non-null datetime64[ns]
utility_x         2475 non-null object
lat               2475 non-null float64
long              2475 non-null float64
utility           2475 non-null object
dtypes: datetime64[ns](1), float64(2), object(10)
memory usage: 270.7+ KB

In [69]:
utils_identified_merge.drop(["utility_x"], axis = 1, inplace = True)

In [71]:
installs_clean.to_csv('clean_data/installs_clean.csv', encoding='utf-8', index=False)